#%RAML 1.0 NamedExample
value:
  -
    id: "1"
    name:
      firstName: "Kuldeep"
      lastName: "rana"
    age: 24
    address: "Dehradun"
  -
    id: "2"
    name:
      firstName: "Saurabh"
      lastName: "mehrotra"
    age: 36
    address: "Noida"